#!/bin/bash

export CDMATH_INSTALL=@CMAKE_INSTALL_PREFIX@
export PETSC_DIR=@PETSC_INSTALL@
export PETSC_ARCH=@PETSC_ARCH@
export PETSC_INCLUDES=@PETSC_INCLUDES_INSTALL@
export PETSC_LIBRARIES=@PETSC_LIBRARIES_INSTALL@
export MEDFILE_ROOT_DIR=@MEDFILE_INSTALL@
export MEDFILE_INCLUDE_DIRS=@MEDFILE_INCLUDES_INSTALL@
export MEDFILE_C_LIBRARIES=@MEDFILE_LIBRARIES_INSTALL@
export MEDCOUPLING_ROOT_DIR=@MEDCOUPLING_INSTALL@
export MEDCOUPLING_INCLUDE_DIR=@MEDCOUPLING_INCLUDES_INSTALL@
export MEDCOUPLING_LIBRARIES=@MEDCOUPLING_LIBRARIES_INSTALL@
export PV_LIB_DIR=@PV_LIB_DIR@
export PV_PYTHON_DIR=@PV_PYTHON_DIR@

export LD_LIBRARY_PATH=$CDMATH_INSTALL/lib:$MEDCOUPLING_LIBRARIES:$MEDFILE_C_LIBRARIES:$PETSC_LIBRARIES:$PV_LIB_DIR:${LD_LIBRARY_PATH}
export PYTHONPATH=$CDMATH_INSTALL/lib/cdmath:$CDMATH_INSTALL/bin/cdmath:$CDMATH_INSTALL/bin/cdmath/postprocessing:$CDMATH_INSTALL/$PV_PYTHON_DIR:${PYTHONPATH}:$MEDCOUPLING_LIBRARIES:$MEDFILE_C_LIBRARIES:$PETSC_LIBRARIES

